CREATE TABLE IF NOT EXISTS api_key (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, last_used_at timestamp(6) with time zone, revoked boolean not null, revoked_at timestamp(6) with time zone, revoked_by varchar(255), title varchar(255) not null, token varchar(255) not null unique, type varchar(255) not null check (type in ('PUBLISHABLE','SECRET')), store_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS app_user (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, avatarUrl varchar(255), email varchar(255) not null unique, emailVerified boolean, firstName varchar(255), isActive boolean not null, lastLoginAt timestamp(6) with time zone, lastName varchar(255), passwordHash varchar(255) not null, primary key (id));
CREATE TABLE IF NOT EXISTS audit_log (id bigint generated by default as identity, action varchar(255) not null check (action in ('CREATE','READ','UPDATE','DELETE','LOGIN','LOGOUT','LOGIN_FAILED','PERMISSION_DENIED')), description TEXT, entityId varchar(255) not null, entityType varchar(255) not null, ipAddress varchar(255), metadata jsonb, newValue TEXT, oldValue TEXT, timestamp timestamp(6) with time zone not null, userAgent varchar(255), userId varchar(255) not null, userName varchar(255), version bigint not null, primary key (id));
CREATE TABLE IF NOT EXISTS brand (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, active boolean not null, description TEXT, logo_url varchar(255), name varchar(255) not null, slug varchar(255) not null, tier varchar(20) not null check (tier in ('LUXURY','PREMIUM','STANDARD')), website_url varchar(255), primary key (id), constraint uk_brand_slug unique (slug));
CREATE TABLE IF NOT EXISTS campaign_execution (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, completed_at timestamp(6) with time zone, emails_failed integer not null, emails_sent integer not null, error_message TEXT, execution_status varchar(255) not null check (execution_status in ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')), started_at timestamp(6) with time zone, workflow_execution_id varchar(255), campaign_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS canonical_category (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, depth integer, name varchar(255) not null, path TEXT, slug varchar(255) not null unique, sort_order integer, parent_id VARCHAR(36), primary key (id));
CREATE TABLE IF NOT EXISTS canonical_category_mapping (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, confidence float(53), external_key varchar(512) not null, external_source varchar(255) not null, notes TEXT, canonical_category_id VARCHAR(36) not null, primary key (id), constraint idx_cat_mapping_source_key unique (external_source, external_key));
CREATE TABLE IF NOT EXISTS canonical_category_synonym (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, name varchar(255) not null unique, category_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS cart (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, billingAddressId varchar(255), completedAt timestamp(6) with time zone, currency_code varchar(3) not null, customer_id varchar(255), discount numeric(19,4) not null, discountTotal numeric(19,4) not null, email varchar(255), note TEXT, paymentMethodId varchar(255), region_id varchar(255) not null, shipping numeric(19,4) not null, address_1 varchar(255), address_2 varchar(255), city varchar(255), country_code varchar(255), phone varchar(255), postal_code varchar(255), province varchar(255), shippingMethodId varchar(255), subtotal numeric(19,4) not null, tax numeric(19,4) not null, taxAmount numeric(19,4) not null, tax_code varchar(255), taxRate numeric(4,4) not null, total numeric(19,4) not null, primary key (id));
CREATE TABLE IF NOT EXISTS cart_line_item (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, allowDiscounts boolean not null, currency_code varchar(3) not null, description varchar(255), discount numeric(19,4), hasShipping boolean, isGiftcard boolean, quantity integer not null, shouldMerge boolean, taxAmount numeric(19,4) not null, tax_code varchar(255), taxRate numeric(4,4) not null, thumbnail varchar(255), title varchar(255) not null, total numeric(19,4) not null, unitPrice numeric(19,4) not null, variant_id varchar(255) not null, cart_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS cj_advertiser_config (id bigint generated by default as identity, advertiser_id bigint not null unique, advertiser_name varchar(255), compression_type varchar(255), created_at timestamp(6) with time zone not null, enabled boolean, feed_format varchar(255), feed_url varchar(2048), metadata jsonb, schedule_cron varchar(255), updated_at timestamp(6) with time zone not null, version integer not null, primary key (id));
CREATE TABLE IF NOT EXISTS cj_feed_config (id bigint generated by default as identity, advertiser_id bigint not null, advertiser_name varchar(255), compression_type varchar(255), created_at timestamp(6) with time zone not null, enabled boolean not null, feed_format varchar(255), feed_name varchar(512) not null, feed_url varchar(2048), language varchar(10), last_sync_at timestamp(6) with time zone, last_sync_run_id varchar(255), last_sync_status varchar(255), metadata jsonb, priority integer not null, region varchar(10), updated_at timestamp(6) with time zone not null, version integer not null, primary key (id), constraint uk_cj_feed_name unique (advertiser_id, feed_name));
CREATE TABLE IF NOT EXISTS cj_feed_run (run_id varchar(255) not null, advertiser_id bigint not null, created_at timestamp(6) with time zone not null, feed_config_id bigint, feed_name varchar(255), finished_at timestamp(6) with time zone, last_updated_at timestamp(6) with time zone not null, processed bigint, started_at timestamp(6) with time zone not null, status varchar(255) not null check (status in ('STARTED','RUNNING','COMPLETED','FAILED','CANCELLING','CANCELLED')), total bigint, updated_at timestamp(6) with time zone not null, version integer not null, primary key (run_id));
CREATE TABLE IF NOT EXISTS country (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, display_name varchar(255) not null, iso_2 varchar(2) not null unique, iso_3 varchar(3) not null unique, name varchar(255) not null unique, num_code integer not null unique, primary key (id), constraint idx_country_iso2 unique (iso2), constraint idx_country_iso3 unique (iso3));
CREATE TABLE IF NOT EXISTS currency (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, code varchar(3) not null unique, decimal_digits integer not null, includes_tax boolean not null, name varchar(255) not null, rounding float(53) not null, symbol varchar(255) not null, symbol_native varchar(255) not null, primary key (id));
CREATE TABLE IF NOT EXISTS customer (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, billingAddressId varchar(255), email varchar(255) not null, firstName varchar(255), hasAccount boolean not null, lastName varchar(255), phone varchar(255), user_id VARCHAR(36) unique, primary key (id));
CREATE TABLE IF NOT EXISTS customer_address (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, address_1 varchar(255) not null, address_2 varchar(255), city varchar(255) not null, company varchar(255), country_code varchar(2) not null, firstName varchar(255), lastName varchar(255), phone varchar(255), postal_code varchar(255), province varchar(255), customer_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS customer_group (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, description TEXT, name varchar(255) not null unique, primary key (id));
CREATE TABLE IF NOT EXISTS customer_group_customers (customer_id VARCHAR(36) not null, customer_group_id VARCHAR(36) not null, primary key (customer_id, customer_group_id));
CREATE TABLE IF NOT EXISTS discount (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, cart_id varchar(255), code varchar(255) not null, is_applied boolean not null, is_valid boolean not null, order_id varchar(255), reason TEXT, type varchar(255) not null check (type in ('PERCENTAGE','FIXED','FREE_SHIPPING')), value float(53) not null, promotion_id VARCHAR(36), primary key (id));
CREATE TABLE IF NOT EXISTS email_log (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, bounced_at timestamp(6) with time zone, click_count integer not null, clicked_at timestamp(6) with time zone, delivered_at timestamp(6) with time zone, email_type varchar(255) not null check (email_type in ('PRICE_DROP','NEW_ARRIVALS','WIN_BACK','WEEKLY_DIGEST','MANUAL')), error_message TEXT, failed_at timestamp(6) with time zone, mailersend_message_id varchar(255), open_count integer not null, opened_at timestamp(6) with time zone, recipient_email varchar(255) not null, sent_at timestamp(6) with time zone, status varchar(255) not null check (status in ('PENDING','SENT','DELIVERED','OPENED','CLICKED','BOUNCED','FAILED','UNSUBSCRIBED')), subject varchar(500) not null, campaign_id VARCHAR(36), campaign_execution_id VARCHAR(36), customer_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS fulfillment (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, canceled_at timestamp(6) with time zone, claim_order_id varchar(255), data jsonb, location_id varchar(255), no_notification boolean not null, note TEXT, order_id varchar(255), shipped_at timestamp(6) with time zone, swap_id varchar(255), tracking_numbers TEXT, tracking_urls TEXT, provider_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS fulfillment_item (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, barcode varchar(100), line_item_id varchar(255) not null, quantity integer not null, sku varchar(100), title varchar(255), fulfillment_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS fulfillment_provider (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, config jsonb, is_active boolean not null, name varchar(255) not null, provider_id varchar(255) not null unique, primary key (id));
CREATE TABLE IF NOT EXISTS inventory_item (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, height integer, hs_code varchar(255), length integer, material varchar(255), mid_code varchar(255), origin_country varchar(255), requires_shipping boolean not null, sku varchar(255) unique, weight integer, width integer, primary key (id));
CREATE TABLE IF NOT EXISTS inventory_level (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, available_quantity integer not null, incoming_quantity integer not null, reserved_quantity integer not null, stocked_quantity integer not null, inventory_item_id VARCHAR(36) not null, location_id VARCHAR(36) not null, primary key (id), constraint idx_inventory_level_item_location unique (inventory_item_id, location_id));
CREATE TABLE IF NOT EXISTS inventory_reservation (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, inventory_level_id varchar(255) not null, line_item_id varchar(255), order_id varchar(255), quantity integer not null, released_at timestamp(6) with time zone, primary key (id));
CREATE TABLE IF NOT EXISTS marketing_campaign (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, campaign_type varchar(255) not null check (campaign_type in ('PRICE_DROP','NEW_ARRIVALS','WIN_BACK','WEEKLY_DIGEST','MANUAL')), completed_at timestamp(6) with time zone, config jsonb, description TEXT, email_preheader varchar(255), email_subject varchar(500) not null, email_template_id varchar(255), name varchar(255) not null, scheduled_at timestamp(6) with time zone, started_at timestamp(6) with time zone, status varchar(255) not null check (status in ('DRAFT','SCHEDULED','RUNNING','PAUSED','COMPLETED','CANCELLED')), target_all_customers boolean not null, total_failed bigint not null, total_recipients bigint not null, total_sent bigint not null, target_customer_group_id VARCHAR(36), primary key (id));
CREATE TABLE IF NOT EXISTS marketing_preference (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, email_frequency varchar(255) not null check (email_frequency in ('DAILY','NORMAL','WEEKLY','MONTHLY')), excludedBrands jsonb, excludedCategories jsonb, marketing_emails_enabled boolean not null, new_arrivals_enabled boolean not null, preferredBrands jsonb, preferredCategories jsonb, price_drop_alerts_enabled boolean not null, promotional_enabled boolean not null, unsubscribe_reason varchar(255), unsubscribed_at timestamp(6) with time zone, weekly_digest_enabled boolean not null, customer_id VARCHAR(36) not null unique, primary key (id));
CREATE TABLE IF NOT EXISTS order_address (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, address1 varchar(255) not null, address2 varchar(255), city varchar(255) not null, company varchar(255), country_code varchar(2) not null, firstName varchar(255), lastName varchar(255), phone varchar(255), postalCode varchar(255), province varchar(255), primary key (id));
CREATE TABLE IF NOT EXISTS order_line_item (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, allowDiscounts boolean not null, currency_code varchar(3) not null, description varchar(255), discount numeric(19,4), fulfilledQuantity integer not null, hasShipping boolean, isGiftcard boolean, quantity integer not null, returnedQuantity integer not null, shippedQuantity integer not null, shouldMerge boolean, status varchar(255) not null check (status in ('PENDING','FULFILLED','SHIPPED','PARTIALLY_SHIPPED','RETURNED','CANCELED')), thumbnail varchar(255), title varchar(255) not null, total numeric(19,4) not null, unitPrice numeric(19,4) not null, variant_id varchar(255), order_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS orders (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, canceledAt varchar(255), cart_id varchar(255), currency_code varchar(3) not null, customer_id varchar(255), discount numeric(19,4) not null, displayId integer not null unique, email varchar(255) not null, fulfillment_status varchar(255) not null check (fulfillment_status in ('NOT_FULFILLED','PARTIALLY_FULFILLED','FULFILLED','PARTIALLY_SHIPPED','SHIPPED','PARTIALLY_RETURNED','RETURNED','CANCELED','REQUIRES_ACTION')), note TEXT, paymentMethodId varchar(255), payment_status varchar(255) not null check (payment_status in ('NOT_PAID','AWAITING','CAPTURED','PARTIALLY_PAID','PAID','PARTIALLY_REFUNDED','REFUNDED','CANCELED','REQUIRES_ACTION')), region_id varchar(255) not null, shipping numeric(19,4) not null, shippingMethodId varchar(255), status varchar(255) not null check (status in ('PENDING','COMPLETED','ARCHIVED','CANCELED','REQUIRES_ACTION')), subtotal numeric(19,4) not null, tax numeric(19,4) not null, total numeric(19,4) not null, billing_address_id VARCHAR(36) unique, shipping_address_id VARCHAR(36) unique, primary key (id));
CREATE TABLE IF NOT EXISTS payment (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, amount_refunded numeric(19,4) not null, authorized_at timestamp(6) with time zone, canceled_at timestamp(6) with time zone, captured_amount numeric(19,4), captured_at timestamp(6) with time zone, cart_id varchar(255), currency_code varchar(3) not null, data jsonb, external_id varchar(255), order_id varchar(255), status varchar(255) not null check (status in ('PENDING','AUTHORIZED','CAPTURED','PARTIALLY_REFUNDED','REFUNDED','CANCELED','FAILED','REQUIRES_ACTION')), payment_collection_id VARCHAR(36), payment_session_id VARCHAR(36) unique, provider_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS payment_collection (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, completed_at timestamp(6) with time zone, currency_code varchar(3) not null, region_id varchar(255), status varchar(255) not null check (status in ('NOT_PAID','PAID','PARTIALLY_PAID','REFUNDED','PARTIALLY_REFUNDED','CANCELED','REQUIRES_ACTION')), primary key (id));
CREATE TABLE IF NOT EXISTS payment_provider (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, config jsonb, is_active boolean not null, is_test_mode boolean not null, name varchar(255) not null, primary key (id));
CREATE TABLE IF NOT EXISTS payment_session (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, authorized_at timestamp(6) with time zone, context TEXT, currency_code varchar(3) not null, data TEXT, payment_collection_id varchar(255) not null, provider_id varchar(255) not null, status varchar(255) not null check (status in ('PENDING','AUTHORIZED','CAPTURED','CANCELED','ERROR','REQUIRES_ACTION')), primary key (id));
CREATE TABLE IF NOT EXISTS permission (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, action varchar(255), description varchar(255), name varchar(255) not null unique, resource varchar(255), primary key (id));
CREATE TABLE IF NOT EXISTS price (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, currency_code varchar(3) not null, is_default boolean not null, max_quantity integer, min_quantity integer, region_id varchar(255), price_set_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS price_set (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, type varchar(255) not null, primary key (id));
CREATE TABLE IF NOT EXISTS product (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, canonical_url varchar(255), description TEXT, discountable boolean not null, externalId varchar(255), external_key varchar(255), extracted_size varchar(255), handle varchar(255) not null unique, height varchar(255), hsCode varchar(255), isGiftcard boolean not null, length varchar(255), material varchar(255), midCode varchar(255), originCountry varchar(255), shipping_profile_id varchar(255), size_type varchar(255), source varchar(255) not null check (source in ('OWNED')), status varchar(255) not null check (status in ('DRAFT','PROPOSED','PUBLISHED','REJECTED')), subtitle varchar(255), thumbnail varchar(255), title varchar(255) not null, weight varchar(255), width varchar(255), brand_id VARCHAR(36), canonical_category_id VARCHAR(36), collection_id VARCHAR(255), type_id VARCHAR(36), primary key (id));
CREATE TABLE IF NOT EXISTS product_category (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, description TEXT, external_id varchar(255) unique, handle varchar(255) not null unique, image varchar(255), isActive boolean not null, isInternal boolean not null, name varchar(255) not null, position integer not null, source varchar(255), parent_category_id VARCHAR(36), primary key (id));
CREATE TABLE IF NOT EXISTS product_category_product (product_id VARCHAR(36) not null, product_category_id VARCHAR(36) not null, primary key (product_id, product_category_id));
CREATE TABLE IF NOT EXISTS product_collection (id VARCHAR(255) not null, created_at timestamp(6) with time zone not null, deleted_at timestamp(6) with time zone, description TEXT, handle varchar(255) not null unique, imageUrl TEXT, metadata jsonb, published boolean not null, title varchar(255) not null unique, updated_at timestamp(6) with time zone not null, primary key (id));
CREATE TABLE IF NOT EXISTS product_image (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, altText varchar(255), height integer, mimeType varchar(255), position integer not null, size bigint, url varchar(255) not null, width integer, product_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS product_option (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, position integer not null, title varchar(255) not null, product_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS product_option_value (option_id VARCHAR(36) not null, value varchar(255) not null, position integer not null, primary key (option_id, position));
CREATE TABLE IF NOT EXISTS product_tag (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, description TEXT, value varchar(255) not null unique, primary key (id));
CREATE TABLE IF NOT EXISTS product_tags (product_id VARCHAR(36) not null, tag_id VARCHAR(36) not null, primary key (product_id, tag_id));
CREATE TABLE IF NOT EXISTS product_type (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, description TEXT, value varchar(255) not null unique, primary key (id));
CREATE TABLE IF NOT EXISTS product_variant (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, allowBackorder boolean not null, barcode varchar(255), ean varchar(255), height varchar(255), hsCode varchar(255), length varchar(255), manageInventory boolean not null, material varchar(255), midCode varchar(255), originCountry varchar(255), sku varchar(255) unique, title varchar(255) not null, upc varchar(255), weight varchar(255), width varchar(255), product_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS product_variant_inventory_item (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, inventory_item_id varchar(255) not null, requiredQuantity integer not null, variant_id VARCHAR(36) not null, primary key (id), constraint uk_variant_inventory_item unique (variant_id, inventory_item_id));
CREATE TABLE IF NOT EXISTS product_variant_option (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, value varchar(255) not null, option_id VARCHAR(36) not null, variant_id VARCHAR(36) not null, primary key (id), constraint uk_variant_option unique (variant_id, option_id));
CREATE TABLE IF NOT EXISTS product_variant_price (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, compareAtPrice numeric(19,4), currencyCode varchar(3) not null, maxQuantity integer, minQuantity integer, regionId varchar(255), variant_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS promotion (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, code varchar(255) not null unique, ends_at timestamp(6) with time zone, is_active boolean not null, is_disabled boolean not null, regions TEXT, starts_at timestamp(6) with time zone, type varchar(255) not null check (type in ('PERCENTAGE','FIXED','FREE_SHIPPING')), usage_count integer not null, usage_limit integer, value float(53) not null, primary key (id));
CREATE TABLE IF NOT EXISTS promotion_rule (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, attribute varchar(255), description TEXT, operator varchar(255), type varchar(255) not null check (type in ('MIN_SUBTOTAL','MIN_QUANTITY','PRODUCT_IDS','PRODUCT_COLLECTIONS','PRODUCT_TYPES','PRODUCT_TAGS','CUSTOMER_GROUPS')), value varchar(255), promotion_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS refund (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, currency_code varchar(3) not null, data jsonb, note TEXT, order_id varchar(255), reason varchar(255) not null check (reason in ('DISCOUNT','RETURN','SWAP','CLAIM','CANCEL','OTHER')), status varchar(255) not null check (status in ('PENDING','SUCCEEDED','FAILED','CANCELED')), payment_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS region (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, automatic_taxes boolean not null, currency_code varchar(255) not null, gift_cards_taxable boolean not null, name varchar(255) not null, tax_code varchar(255), tax_inclusive boolean not null, tax_rate numeric(10,4), primary key (id), constraint idx_region_name unique (name));
CREATE TABLE IF NOT EXISTS region_country (region_id VARCHAR(36) not null, country_id VARCHAR(36) not null, primary key (region_id, country_id));
CREATE TABLE IF NOT EXISTS region_fulfillment_provider (region_id VARCHAR(36) not null, fulfillment_provider_id VARCHAR(36) not null, primary key (region_id, fulfillment_provider_id));
CREATE TABLE IF NOT EXISTS region_payment_provider (region_id VARCHAR(36) not null, payment_provider_id VARCHAR(36) not null, primary key (region_id, payment_provider_id));
CREATE TABLE IF NOT EXISTS role (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, description varchar(255), name varchar(255) not null unique, primary key (id));
CREATE TABLE IF NOT EXISTS role_permission (role_id VARCHAR(36) not null, permission_id VARCHAR(36) not null, primary key (role_id, permission_id));
CREATE TABLE IF NOT EXISTS sales_channel (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, description TEXT, is_active boolean not null, is_disabled boolean not null, name varchar(255) not null, store_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS shipping_option (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, amount numeric(19,4) not null, data jsonb, is_active boolean not null, is_return boolean not null, name varchar(255) not null, price_type varchar(255) not null check (price_type in ('FLAT_RATE','CALCULATED')), region_id varchar(255) not null, requirements jsonb, profile_id VARCHAR(36) not null, provider_id VARCHAR(36), primary key (id));
CREATE TABLE IF NOT EXISTS shipping_profile (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, name varchar(255) not null, product_ids TEXT[], type varchar(255) not null check (type in ('DEFAULT','GIFT_CARD','CUSTOM')), primary key (id));
CREATE TABLE IF NOT EXISTS stock_location (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, address TEXT, address_1 varchar(255), address_2 varchar(255), city varchar(255), country_code varchar(2), fulfillment_enabled boolean not null, name varchar(255) not null, phone varchar(255), postal_code varchar(255), priority integer not null, province varchar(255), primary key (id));
CREATE TABLE IF NOT EXISTS store (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, default_currency_code varchar(3) not null, default_location_id varchar(255), default_region_id varchar(255), default_sales_channel_id varchar(255), invite_link_template varchar(255), name varchar(255) not null, payment_link_template varchar(255), swap_link_template varchar(255), primary key (id));
CREATE TABLE IF NOT EXISTS store_currency (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, currency_code varchar(3) not null, is_default boolean not null, store_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS tax_rate (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, code varchar(255), name varchar(255) not null, product_categories TEXT, product_types TEXT, rate float(53) not null, shipping_option_id varchar(255), region_id VARCHAR(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS user_activity_log (id varchar(36) not null, activity_type varchar(255) not null check (activity_type in ('PAGE_VIEW','PRODUCT_VIEW','SEARCH','FAVORITE_ADD','CLICK_OUT')), brand_id varchar(36), category_id varchar(36), created_at timestamp(6) with time zone not null, metadata jsonb, product_id varchar(36), session_id varchar(255), user_id varchar(36) not null, primary key (id));
CREATE TABLE IF NOT EXISTS user_brand_follow (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, brand_id VARCHAR(36) not null, user_id VARCHAR(36) not null, primary key (id), constraint uk_user_brand_follow_user_brand unique (user_id, brand_id));
CREATE TABLE IF NOT EXISTS user_brand_interest (id varchar(36) not null, created_at timestamp(6) with time zone not null, interest_score integer not null, last_interaction_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, user_id varchar(36) not null, brand_id VARCHAR(36) not null, primary key (id), constraint uk_user_brand_interest unique (user_id, brand_id));
CREATE TABLE IF NOT EXISTS user_favorite (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, alert_enabled boolean not null, price_threshold numeric(38,2), product_id VARCHAR(36) not null, user_id VARCHAR(36) not null, primary key (id), constraint uk_user_favorite_user_product unique (user_id, product_id));
CREATE TABLE IF NOT EXISTS user_role (user_id VARCHAR(36) not null, role_id VARCHAR(36) not null, primary key (user_id, role_id));
CREATE TABLE IF NOT EXISTS user_size_preference (id VARCHAR(36) not null, createdAt timestamp(6) with time zone not null, createdBy varchar(255), deletedAt timestamp(6) with time zone, deletedBy varchar(255), metadata jsonb, updatedAt timestamp(6) with time zone not null, updatedBy varchar(255), version bigint not null, size varchar(255) not null, user_id VARCHAR(36) not null, primary key (id), constraint uk_user_size_preference_user_size unique (user_id, size));
CREATE INDEX IF NOT EXISTS idx_api_key_store_id on api_key (store_id);
CREATE INDEX IF NOT EXISTS idx_api_key_revoked on api_key (revoked);
CREATE INDEX IF NOT EXISTS idx_api_key_deleted_at on api_key (deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_deleted_at on app_user (deleted_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity on audit_log (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_user on audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp on audit_log (timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_action on audit_log (action);
CREATE INDEX IF NOT EXISTS idx_brand_name on brand (name);
CREATE INDEX IF NOT EXISTS idx_brand_slug_active on brand (slug, deleted_at);
CREATE INDEX IF NOT EXISTS idx_campaign_execution_campaign on campaign_execution (campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_execution_status on campaign_execution (execution_status, started_at);
CREATE INDEX IF NOT EXISTS idx_canonical_category_parent on canonical_category (parent_id);
CREATE INDEX IF NOT EXISTS idx_cat_mapping_canonical on canonical_category_mapping (canonical_category_id);
CREATE INDEX IF NOT EXISTS idx_canonical_synonym_category on canonical_category_synonym (category_id);
CREATE INDEX IF NOT EXISTS idx_cart_customer_id on cart (customer_id);
CREATE INDEX IF NOT EXISTS idx_cart_email on cart (email);
CREATE INDEX IF NOT EXISTS idx_cart_region_id on cart (region_id);
CREATE INDEX IF NOT EXISTS idx_cart_completed_at on cart (completed_at);
CREATE INDEX IF NOT EXISTS idx_cart_deleted_at on cart (deleted_at);
CREATE INDEX IF NOT EXISTS idx_cart_line_item_cart_id on cart_line_item (cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_line_item_variant_id on cart_line_item (variant_id);
CREATE INDEX IF NOT EXISTS idx_cart_line_item_deleted_at on cart_line_item (deleted_at);
CREATE INDEX IF NOT EXISTS idx_cj_feed_advertiser on cj_feed_config (advertiser_id);
CREATE INDEX IF NOT EXISTS idx_cj_feed_enabled on cj_feed_config (enabled);
CREATE INDEX IF NOT EXISTS idx_cj_feed_name on cj_feed_config (feed_name);
CREATE INDEX IF NOT EXISTS idx_currency_deleted_at on currency (deleted_at);
CREATE INDEX IF NOT EXISTS idx_customer_email on customer (email);
CREATE INDEX IF NOT EXISTS idx_customer_phone on customer (phone);
CREATE INDEX IF NOT EXISTS idx_customer_has_account on customer (has_account);
CREATE INDEX IF NOT EXISTS idx_customer_deleted_at on customer (deleted_at);
CREATE INDEX IF NOT EXISTS idx_customer_address_customer_id on customer_address (customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_address_country_code on customer_address (country_code);
CREATE INDEX IF NOT EXISTS idx_customer_address_deleted_at on customer_address (deleted_at);
CREATE INDEX IF NOT EXISTS idx_customer_group_deleted_at on customer_group (deleted_at);
CREATE INDEX IF NOT EXISTS idx_discount_order_id on discount (order_id);
CREATE INDEX IF NOT EXISTS idx_discount_cart_id on discount (cart_id);
CREATE INDEX IF NOT EXISTS idx_discount_promotion_id on discount (promotion_id);
CREATE INDEX IF NOT EXISTS idx_discount_deleted_at on discount (deleted_at);
CREATE INDEX IF NOT EXISTS idx_email_log_customer on email_log (customer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_email_log_campaign on email_log (campaign_id, status);
CREATE INDEX IF NOT EXISTS idx_email_log_status on email_log (status, sent_at);
CREATE INDEX IF NOT EXISTS idx_email_log_mailersend on email_log (mailersend_message_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_order_id on fulfillment (order_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_claim_order_id on fulfillment (claim_order_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_swap_id on fulfillment (swap_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_provider_id on fulfillment (provider_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_location_id on fulfillment (location_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_tracking_numbers on fulfillment (tracking_numbers);
CREATE INDEX IF NOT EXISTS idx_fulfillment_deleted_at on fulfillment (deleted_at);
CREATE INDEX IF NOT EXISTS idx_fulfillment_item_fulfillment_id on fulfillment_item (fulfillment_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_item_line_item_id on fulfillment_item (line_item_id);
CREATE INDEX IF NOT EXISTS idx_fulfillment_item_deleted_at on fulfillment_item (deleted_at);
CREATE INDEX IF NOT EXISTS idx_fulfillment_provider_is_active on fulfillment_provider (is_active);
CREATE INDEX IF NOT EXISTS idx_fulfillment_provider_deleted_at on fulfillment_provider (deleted_at);
CREATE INDEX IF NOT EXISTS idx_inventory_item_origin_country on inventory_item (origin_country);
CREATE INDEX IF NOT EXISTS idx_inventory_item_deleted_at on inventory_item (deleted_at);
CREATE INDEX IF NOT EXISTS idx_inventory_level_inventory_item_id on inventory_level (inventory_item_id);
CREATE INDEX IF NOT EXISTS idx_inventory_level_location_id on inventory_level (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_level_deleted_at on inventory_level (deleted_at);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_order_id on inventory_reservation (order_id);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_line_item_id on inventory_reservation (line_item_id);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_level_id on inventory_reservation (inventory_level_id);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_deleted_at on inventory_reservation (deleted_at);
CREATE INDEX IF NOT EXISTS idx_campaign_type_status on marketing_campaign (campaign_type, status, deleted_at);
CREATE INDEX IF NOT EXISTS idx_campaign_scheduled on marketing_campaign (scheduled_at, status);
CREATE INDEX IF NOT EXISTS idx_campaign_created on marketing_campaign (created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_pref_enabled on marketing_preference (marketing_emails_enabled);
CREATE INDEX IF NOT EXISTS idx_order_address_country_code on order_address (country_code);
CREATE INDEX IF NOT EXISTS idx_order_address_deleted_at on order_address (deleted_at);
CREATE INDEX IF NOT EXISTS idx_order_line_item_order_id on order_line_item (order_id);
CREATE INDEX IF NOT EXISTS idx_order_line_item_variant_id on order_line_item (variant_id);
CREATE INDEX IF NOT EXISTS idx_order_line_item_deleted_at on order_line_item (deleted_at);
CREATE INDEX IF NOT EXISTS idx_payment_order_id on payment (order_id);
CREATE INDEX IF NOT EXISTS idx_payment_cart_id on payment (cart_id);
CREATE INDEX IF NOT EXISTS idx_payment_provider_id on payment (provider_id);
CREATE INDEX IF NOT EXISTS idx_payment_status on payment (status);
CREATE INDEX IF NOT EXISTS idx_payment_external_id on payment (external_id);
CREATE INDEX IF NOT EXISTS idx_payment_deleted_at on payment (deleted_at);
CREATE INDEX IF NOT EXISTS idx_payment_collection_currency_code on payment_collection (currency_code);
CREATE INDEX IF NOT EXISTS idx_payment_collection_region_id on payment_collection (region_id);
CREATE INDEX IF NOT EXISTS idx_payment_collection_status on payment_collection (status);
CREATE INDEX IF NOT EXISTS idx_payment_provider_is_active on payment_provider (is_active);
CREATE INDEX IF NOT EXISTS idx_payment_provider_deleted_at on payment_provider (deleted_at);
CREATE INDEX IF NOT EXISTS idx_payment_session_payment_collection_id on payment_session (payment_collection_id);
CREATE INDEX IF NOT EXISTS idx_payment_session_provider_id on payment_session (provider_id);
CREATE INDEX IF NOT EXISTS idx_payment_session_status on payment_session (status);
CREATE INDEX IF NOT EXISTS idx_permission_deleted_at on permission (deleted_at);
CREATE INDEX IF NOT EXISTS idx_price_currency_code on price (currency_code);
CREATE INDEX IF NOT EXISTS idx_price_region_id on price (region_id);
CREATE INDEX IF NOT EXISTS idx_price_price_set_id on price (price_set_id);
CREATE INDEX IF NOT EXISTS idx_price_deleted_at on price (deleted_at);
CREATE INDEX IF NOT EXISTS idx_price_set_type on price_set (type);
CREATE INDEX IF NOT EXISTS idx_price_set_deleted_at on price_set (deleted_at);
CREATE INDEX IF NOT EXISTS idx_product_status on product (status);
CREATE INDEX IF NOT EXISTS idx_product_collection_id on product (collection_id);
CREATE INDEX IF NOT EXISTS idx_product_type_id on product (type_id);
CREATE INDEX IF NOT EXISTS idx_product_deleted_at on product (deleted_at);
CREATE INDEX IF NOT EXISTS idx_product_extracted_size on product (extracted_size);
CREATE INDEX IF NOT EXISTS idx_product_size_type on product (size_type);
CREATE INDEX IF NOT EXISTS idx_category_parent_id on product_category (parent_category_id);
CREATE INDEX IF NOT EXISTS idx_category_active on product_category (is_active);
CREATE INDEX IF NOT EXISTS idx_category_deleted_at on product_category (deleted_at);
CREATE INDEX IF NOT EXISTS idx_product_image_product_id on product_image (product_id);
CREATE INDEX IF NOT EXISTS idx_product_image_url on product_image (url);
CREATE INDEX IF NOT EXISTS idx_product_image_deleted_at on product_image (deleted_at);
CREATE INDEX IF NOT EXISTS idx_product_option_product_id on product_option (product_id);
CREATE INDEX IF NOT EXISTS idx_product_option_deleted_at on product_option (deleted_at);
CREATE INDEX IF NOT EXISTS idx_tag_deleted_at on product_tag (deleted_at);
CREATE INDEX IF NOT EXISTS idx_type_deleted_at on product_type (deleted_at);
CREATE INDEX IF NOT EXISTS idx_variant_product_id on product_variant (product_id);
CREATE INDEX IF NOT EXISTS idx_variant_deleted_at on product_variant (deleted_at);
CREATE INDEX IF NOT EXISTS idx_variant_inventory_variant_id on product_variant_inventory_item (variant_id);
CREATE INDEX IF NOT EXISTS idx_variant_inventory_inventory_item_id on product_variant_inventory_item (inventory_item_id);
CREATE INDEX IF NOT EXISTS idx_variant_inventory_deleted_at on product_variant_inventory_item (deleted_at);
CREATE INDEX IF NOT EXISTS idx_variant_option_variant_id on product_variant_option (variant_id);
CREATE INDEX IF NOT EXISTS idx_variant_option_option_id on product_variant_option (option_id);
CREATE INDEX IF NOT EXISTS idx_variant_option_deleted_at on product_variant_option (deleted_at);
CREATE INDEX IF NOT EXISTS idx_price_variant_id on product_variant_price (variant_id);
CREATE INDEX IF NOT EXISTS idx_price_currency_region on product_variant_price (currency_code, region_id);
CREATE INDEX IF NOT EXISTS idx_promotion_is_active on promotion (is_active);
CREATE INDEX IF NOT EXISTS idx_promotion_starts_at on promotion (starts_at);
CREATE INDEX IF NOT EXISTS idx_promotion_ends_at on promotion (ends_at);
CREATE INDEX IF NOT EXISTS idx_promotion_deleted_at on promotion (deleted_at);
CREATE INDEX IF NOT EXISTS idx_promotion_rule_promotion_id on promotion_rule (promotion_id);
CREATE INDEX IF NOT EXISTS idx_promotion_rule_type on promotion_rule (type);
CREATE INDEX IF NOT EXISTS idx_promotion_rule_deleted_at on promotion_rule (deleted_at);
CREATE INDEX IF NOT EXISTS idx_refund_payment_id on refund (payment_id);
CREATE INDEX IF NOT EXISTS idx_refund_order_id on refund (order_id);
CREATE INDEX IF NOT EXISTS idx_refund_status on refund (status);
CREATE INDEX IF NOT EXISTS idx_refund_deleted_at on refund (deleted_at);
CREATE INDEX IF NOT EXISTS idx_region_currency on region (currency_code);
CREATE INDEX IF NOT EXISTS idx_role_deleted_at on role (deleted_at);
CREATE INDEX IF NOT EXISTS idx_sales_channel_name on sales_channel (name);
CREATE INDEX IF NOT EXISTS idx_sales_channel_store_id on sales_channel (store_id);
CREATE INDEX IF NOT EXISTS idx_sales_channel_is_active on sales_channel (is_active);
CREATE INDEX IF NOT EXISTS idx_sales_channel_deleted_at on sales_channel (deleted_at);
CREATE INDEX IF NOT EXISTS idx_shipping_option_region_id on shipping_option (region_id);
CREATE INDEX IF NOT EXISTS idx_shipping_option_profile_id on shipping_option (profile_id);
CREATE INDEX IF NOT EXISTS idx_shipping_option_provider_id on shipping_option (provider_id);
CREATE INDEX IF NOT EXISTS idx_shipping_option_is_active on shipping_option (is_active);
CREATE INDEX IF NOT EXISTS idx_shipping_option_deleted_at on shipping_option (deleted_at);
CREATE INDEX IF NOT EXISTS idx_shipping_profile_name on shipping_profile (name);
CREATE INDEX IF NOT EXISTS idx_shipping_profile_type on shipping_profile (type);
CREATE INDEX IF NOT EXISTS idx_shipping_profile_deleted_at on shipping_profile (deleted_at);
CREATE INDEX IF NOT EXISTS idx_stock_location_name on stock_location (name);
CREATE INDEX IF NOT EXISTS idx_stock_location_deleted_at on stock_location (deleted_at);
CREATE INDEX IF NOT EXISTS idx_store_name on store (name);
CREATE INDEX IF NOT EXISTS idx_store_default_currency_code on store (default_currency_code);
CREATE INDEX IF NOT EXISTS idx_store_deleted_at on store (deleted_at);
CREATE INDEX IF NOT EXISTS idx_store_currency_code on store_currency (currency_code);
CREATE INDEX IF NOT EXISTS idx_store_currency_store_id on store_currency (store_id);
CREATE INDEX IF NOT EXISTS idx_store_currency_is_default on store_currency (is_default);
CREATE INDEX IF NOT EXISTS idx_store_currency_deleted_at on store_currency (deleted_at);
CREATE INDEX IF NOT EXISTS idx_tax_rate_region_id on tax_rate (region_id);
CREATE INDEX IF NOT EXISTS idx_tax_rate_code on tax_rate (code);
CREATE INDEX IF NOT EXISTS idx_tax_rate_deleted_at on tax_rate (deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_activity_user_time on user_activity_log (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_user_activity_type on user_activity_log (activity_type, created_at);
CREATE INDEX IF NOT EXISTS idx_user_brand_follow_user on user_brand_follow (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_brand_follow_brand on user_brand_follow (brand_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_brand_interest_user on user_brand_interest (user_id, interest_score);
CREATE INDEX IF NOT EXISTS idx_brand_interest_brand on user_brand_interest (brand_id, interest_score);
CREATE INDEX IF NOT EXISTS idx_user_favorite_user on user_favorite (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_favorite_product on user_favorite (product_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_size_preference_user on user_size_preference (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_size_preference_size on user_size_preference (size, deleted_at);
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK8s3vws99yff4giqafk3pbtpa6'
    ) THEN
        alter table if exists api_key add constraint FK8s3vws99yff4giqafk3pbtpa6 foreign key (store_id) references store;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKg7qup7s8fwn59hlw47hh2tsht'
    ) THEN
        alter table if exists campaign_execution add constraint FKg7qup7s8fwn59hlw47hh2tsht foreign key (campaign_id) references marketing_campaign;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKkfvdr9b5g0ucbofdrgafpm5ud'
    ) THEN
        alter table if exists canonical_category add constraint FKkfvdr9b5g0ucbofdrgafpm5ud foreign key (parent_id) references canonical_category;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKasvucwq7csl82h6hkc0rp9xqe'
    ) THEN
        alter table if exists canonical_category_mapping add constraint FKasvucwq7csl82h6hkc0rp9xqe foreign key (canonical_category_id) references canonical_category;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKrxa45ocylu9e4vsq2b7sk6uts'
    ) THEN
        alter table if exists canonical_category_synonym add constraint FKrxa45ocylu9e4vsq2b7sk6uts foreign key (category_id) references canonical_category;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKc81uybcncl96vet9380wa6y5'
    ) THEN
        alter table if exists cart_line_item add constraint FKc81uybcncl96vet9380wa6y5 foreign key (cart_id) references cart;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKslkyb5dphxe4c7au3hqx3la6m'
    ) THEN
        alter table if exists customer add constraint FKslkyb5dphxe4c7au3hqx3la6m foreign key (user_id) references app_user;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKr9ofa0ydsgbaqmt9leb3v5eii'
    ) THEN
        alter table if exists customer_address add constraint FKr9ofa0ydsgbaqmt9leb3v5eii foreign key (customer_id) references customer;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKonlpmt74ao7rrlomtw19qta8l'
    ) THEN
        alter table if exists customer_group_customers add constraint FKonlpmt74ao7rrlomtw19qta8l foreign key (customer_group_id) references customer_group;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKtanpgm9ig9yv1uby5seqa5t3v'
    ) THEN
        alter table if exists customer_group_customers add constraint FKtanpgm9ig9yv1uby5seqa5t3v foreign key (customer_id) references customer;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKfielbo0ak7p61w0wflo4lrqal'
    ) THEN
        alter table if exists discount add constraint FKfielbo0ak7p61w0wflo4lrqal foreign key (promotion_id) references promotion;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK18pn902to2f6qmj24kgmf6suo'
    ) THEN
        alter table if exists email_log add constraint FK18pn902to2f6qmj24kgmf6suo foreign key (campaign_id) references marketing_campaign;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKef15mlh6eu1f3iatrt5sx23rc'
    ) THEN
        alter table if exists email_log add constraint FKef15mlh6eu1f3iatrt5sx23rc foreign key (campaign_execution_id) references campaign_execution;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKjp0cyuls6org402xio1gpdlyd'
    ) THEN
        alter table if exists email_log add constraint FKjp0cyuls6org402xio1gpdlyd foreign key (customer_id) references customer;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK6kfpvak8l93j32ibq3jnde964'
    ) THEN
        alter table if exists fulfillment add constraint FK6kfpvak8l93j32ibq3jnde964 foreign key (provider_id) references fulfillment_provider;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK5p2oelb3wie05dwgsjg89mqve'
    ) THEN
        alter table if exists fulfillment_item add constraint FK5p2oelb3wie05dwgsjg89mqve foreign key (fulfillment_id) references fulfillment;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKevpsykphj50jw1p1tbhc9bny6'
    ) THEN
        alter table if exists inventory_level add constraint FKevpsykphj50jw1p1tbhc9bny6 foreign key (inventory_item_id) references inventory_item;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK34l9ak2id2klil14uy16jt9u'
    ) THEN
        alter table if exists inventory_level add constraint FK34l9ak2id2klil14uy16jt9u foreign key (location_id) references stock_location;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKcvdv9ktsk38hoxd4fwxnbca2h'
    ) THEN
        alter table if exists marketing_campaign add constraint FKcvdv9ktsk38hoxd4fwxnbca2h foreign key (target_customer_group_id) references customer_group;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKfvejgn79pn6grvg36pd3x76lc'
    ) THEN
        alter table if exists marketing_preference add constraint FKfvejgn79pn6grvg36pd3x76lc foreign key (customer_id) references customer;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKbgsq1dd0vi98leb4g7irlei84'
    ) THEN
        alter table if exists order_line_item add constraint FKbgsq1dd0vi98leb4g7irlei84 foreign key (order_id) references orders;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKeo601op4n6j29dhhwvgiygcpd'
    ) THEN
        alter table if exists orders add constraint FKeo601op4n6j29dhhwvgiygcpd foreign key (billing_address_id) references order_address;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK7yfiyiyksmkbspbkw8fj2669q'
    ) THEN
        alter table if exists orders add constraint FK7yfiyiyksmkbspbkw8fj2669q foreign key (shipping_address_id) references order_address;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKkd20cahrl13x37tqyh4mptjk'
    ) THEN
        alter table if exists payment add constraint FKkd20cahrl13x37tqyh4mptjk foreign key (payment_collection_id) references payment_collection;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKbfd7xc5nbeptql5jibmup8wuv'
    ) THEN
        alter table if exists payment add constraint FKbfd7xc5nbeptql5jibmup8wuv foreign key (payment_session_id) references payment_session;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKpriteilvki10mo1lcfq6ln56p'
    ) THEN
        alter table if exists payment add constraint FKpriteilvki10mo1lcfq6ln56p foreign key (provider_id) references payment_provider;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKsehjhky5xn3294hl2fqa0cnj0'
    ) THEN
        alter table if exists price add constraint FKsehjhky5xn3294hl2fqa0cnj0 foreign key (price_set_id) references price_set;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKs6cydsualtsrprvlf2bb3lcam'
    ) THEN
        alter table if exists product add constraint FKs6cydsualtsrprvlf2bb3lcam foreign key (brand_id) references brand;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKjoyegqdv1fi92sc5bqxhpa8fp'
    ) THEN
        alter table if exists product add constraint FKjoyegqdv1fi92sc5bqxhpa8fp foreign key (canonical_category_id) references canonical_category;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKdpd80w48pf73ty00hlqf6gf0'
    ) THEN
        alter table if exists product add constraint FKdpd80w48pf73ty00hlqf6gf0 foreign key (collection_id) references product_collection;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKajjopj7ffr42w11bav8gut0cp'
    ) THEN
        alter table if exists product add constraint FKajjopj7ffr42w11bav8gut0cp foreign key (type_id) references product_type;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKh9b72s73v7cga3g5pff7xryvi'
    ) THEN
        alter table if exists product_category add constraint FKh9b72s73v7cga3g5pff7xryvi foreign key (parent_category_id) references product_category;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK66ul5lfm90ujhahulnnwmootw'
    ) THEN
        alter table if exists product_category_product add constraint FK66ul5lfm90ujhahulnnwmootw foreign key (product_category_id) references product_category;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKooj7nttwg6qcja3iiejtyt1k3'
    ) THEN
        alter table if exists product_category_product add constraint FKooj7nttwg6qcja3iiejtyt1k3 foreign key (product_id) references product;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK6oo0cvcdtb6qmwsga468uuukk'
    ) THEN
        alter table if exists product_image add constraint FK6oo0cvcdtb6qmwsga468uuukk foreign key (product_id) references product;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKn4hmm6ex1vgn60c6uiqte400f'
    ) THEN
        alter table if exists product_option add constraint FKn4hmm6ex1vgn60c6uiqte400f foreign key (product_id) references product;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKk4l49ytji411exnlebxbbq38m'
    ) THEN
        alter table if exists product_option_value add constraint FKk4l49ytji411exnlebxbbq38m foreign key (option_id) references product_option;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK7f5eu6iito2htsvnmp5he9lvn'
    ) THEN
        alter table if exists product_tags add constraint FK7f5eu6iito2htsvnmp5he9lvn foreign key (tag_id) references product_tag;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK8gmf959fnpxtkagtk56mbaj0e'
    ) THEN
        alter table if exists product_tags add constraint FK8gmf959fnpxtkagtk56mbaj0e foreign key (product_id) references product;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKgrbbs9t374m9gg43l6tq1xwdj'
    ) THEN
        alter table if exists product_variant add constraint FKgrbbs9t374m9gg43l6tq1xwdj foreign key (product_id) references product;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKqpmmuovmgohpsjphd7oyufmhv'
    ) THEN
        alter table if exists product_variant_inventory_item add constraint FKqpmmuovmgohpsjphd7oyufmhv foreign key (variant_id) references product_variant;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKj09uyuastoaaf95i9a5xy0q8k'
    ) THEN
        alter table if exists product_variant_option add constraint FKj09uyuastoaaf95i9a5xy0q8k foreign key (option_id) references product_option;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKplhcd8aya55o6c5b9vfwcj64x'
    ) THEN
        alter table if exists product_variant_option add constraint FKplhcd8aya55o6c5b9vfwcj64x foreign key (variant_id) references product_variant;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKjpjr00h82m6bgmksit5h1rnc7'
    ) THEN
        alter table if exists product_variant_price add constraint FKjpjr00h82m6bgmksit5h1rnc7 foreign key (variant_id) references product_variant;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKaqnxihpss22fi7tvnh2rg8muw'
    ) THEN
        alter table if exists promotion_rule add constraint FKaqnxihpss22fi7tvnh2rg8muw foreign key (promotion_id) references promotion;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKeoh1147brjy6m009cswl5lty4'
    ) THEN
        alter table if exists refund add constraint FKeoh1147brjy6m009cswl5lty4 foreign key (payment_id) references payment;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKt72fux40a72ellahac1rwme34'
    ) THEN
        alter table if exists region_country add constraint FKt72fux40a72ellahac1rwme34 foreign key (country_id) references country;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK772ycsc3furqgjv70d9nf9lbk'
    ) THEN
        alter table if exists region_country add constraint FK772ycsc3furqgjv70d9nf9lbk foreign key (region_id) references region;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKhjuscgtju01xjp31o94di5l25'
    ) THEN
        alter table if exists region_fulfillment_provider add constraint FKhjuscgtju01xjp31o94di5l25 foreign key (fulfillment_provider_id) references fulfillment_provider;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKs4ymtyx4p6oh9iah3sfjs57cq'
    ) THEN
        alter table if exists region_fulfillment_provider add constraint FKs4ymtyx4p6oh9iah3sfjs57cq foreign key (region_id) references region;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKr3h12kim5sjh6cjxprckpgdcq'
    ) THEN
        alter table if exists region_payment_provider add constraint FKr3h12kim5sjh6cjxprckpgdcq foreign key (payment_provider_id) references payment_provider;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK55u7gkybqpu4vwb6qxl8y3fhx'
    ) THEN
        alter table if exists region_payment_provider add constraint FK55u7gkybqpu4vwb6qxl8y3fhx foreign key (region_id) references region;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKf8yllw1ecvwqy3ehyxawqa1qp'
    ) THEN
        alter table if exists role_permission add constraint FKf8yllw1ecvwqy3ehyxawqa1qp foreign key (permission_id) references permission;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKa6jx8n8xkesmjmv6jqug6bg68'
    ) THEN
        alter table if exists role_permission add constraint FKa6jx8n8xkesmjmv6jqug6bg68 foreign key (role_id) references role;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKjx2itgp6abay9msw490n95nh7'
    ) THEN
        alter table if exists sales_channel add constraint FKjx2itgp6abay9msw490n95nh7 foreign key (store_id) references store;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKii4vh72n3vj4ann6243gqoc5l'
    ) THEN
        alter table if exists shipping_option add constraint FKii4vh72n3vj4ann6243gqoc5l foreign key (profile_id) references shipping_profile;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKma5wby4npmqoxhoielg31twob'
    ) THEN
        alter table if exists shipping_option add constraint FKma5wby4npmqoxhoielg31twob foreign key (provider_id) references fulfillment_provider;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKj20daf2x0b38gc5v6oc81uub6'
    ) THEN
        alter table if exists store_currency add constraint FKj20daf2x0b38gc5v6oc81uub6 foreign key (store_id) references store;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK3fcj26ebw7dbrp5jn4gkqgdqq'
    ) THEN
        alter table if exists tax_rate add constraint FK3fcj26ebw7dbrp5jn4gkqgdqq foreign key (region_id) references region;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKppdpb8r70f5drdpu1xumkrmnh'
    ) THEN
        alter table if exists user_brand_follow add constraint FKppdpb8r70f5drdpu1xumkrmnh foreign key (brand_id) references brand;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKrucaurjnyk21jydyi51alctpb'
    ) THEN
        alter table if exists user_brand_follow add constraint FKrucaurjnyk21jydyi51alctpb foreign key (user_id) references app_user;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKo0d0lgs2fb84ph36dlpoef1wl'
    ) THEN
        alter table if exists user_brand_interest add constraint FKo0d0lgs2fb84ph36dlpoef1wl foreign key (brand_id) references brand;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKd0d0pjggcsl5dlbcuwloys114'
    ) THEN
        alter table if exists user_favorite add constraint FKd0d0pjggcsl5dlbcuwloys114 foreign key (product_id) references product;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKskxuha6p1cyvw36uworh62q5u'
    ) THEN
        alter table if exists user_favorite add constraint FKskxuha6p1cyvw36uworh62q5u foreign key (user_id) references app_user;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKa68196081fvovjhkek5m97n3y'
    ) THEN
        alter table if exists user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FKg7fr1r7o0fkk41nfhnjdyqn7b'
    ) THEN
        alter table if exists user_role add constraint FKg7fr1r7o0fkk41nfhnjdyqn7b foreign key (user_id) references app_user;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK57yect3sjktjxfp9knvqgh7bx'
    ) THEN
        alter table if exists user_size_preference add constraint FK57yect3sjktjxfp9knvqgh7bx foreign key (user_id) references app_user;
    END IF;
END $$;
